modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="infinity"
displayName="Pugmeowlas Infinity Stones Core"
version="2.1"
logoFile = "logo.png"
logoBlur = false
description='''
Unofficial Successor to Infinity Craft, made by Pugmeowla
'''

[[dependencies.test]]
modId = "palladium"
mandatory = true
versionRange = ""
ordering = "NONE"
side = "BOTH"